api_keys:
  hunter_io: YOUR_HUNTER_IO_API_KEY
  neverbounce: YOUR_NEVERBOUNCE_API_KEY
  anymailfinder: YOUR_ANYMAILFINDER_API_KEY

endpoints:
  hunter_io: "https://api.hunter.io/v2"
  neverbounce: "https://api.neverbounce.com/v4"
  anymailfinder: "https://api.anymailfinder.com/v4"